# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - invoice-automation-app

on:
  push:
    branches:
      - dev
      - 'feature/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'invoice-automation-app' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.12' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  BuildDeploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #Required for federated token
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Show current directory and contents
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          echo "Zipping function app contents..."
          zip -r release.zip . -x "venv/*" ".venv/*" ".git/*" ".vscode/*" "__pycache__/*" "*.pyc" "*.pyo" "*.pyd"
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la  

      - name: Import smoke test
        shell: bash
        run: |
          echo "Testing import of function_app.py"
          set -ex
          PYTHONPATH=.python_packages/lib/site-packages python -c "import function_app"

      # - name: Unzip artifact into staging directory for deploymentt
      #   run: |
      #     echo "Current directory:"
      #     pwd
      #     echo "Contents:"
      #     ls -la
        
      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Show Current Dir & Show AZ account status
      #   run: |
      #     echo "Current directory:"
      #     pwd
      #     echo "Contents:"
      #     ls -la
      #     az account show
      #     az group list

      - name: 'Deploy to Azure Functions'
        run: |
          az functionapp deployment source config-zip \
          --resource-group "rg-invoice-automation" \
          --name "invoice-automation-app" \
          --slot "staging" \
          --src "release.zip" \
          
      # - name: Check release.zip files after deployment
      #   run: unzip -l release.zip    
